// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/feed.proto

package Feed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedRequest) Reset() {
	*x = GetFeedRequest{}
	mi := &file_proto_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedRequest) ProtoMessage() {}

func (x *GetFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedRequest.ProtoReflect.Descriptor instead.
func (*GetFeedRequest) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{0}
}

func (x *GetFeedRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetFeedResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Title         string                       `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Images        []*GetFeedResponse_Image     `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	Authors       []*GetFeedResponse_Person    `protobuf:"bytes,4,rep,name=authors,proto3" json:"authors,omitempty"`
	Enclosures    []*GetFeedResponse_Enclosure `protobuf:"bytes,5,rep,name=enclosures,proto3" json:"enclosures,omitempty"`
	Links         []string                     `protobuf:"bytes,6,rep,name=links,proto3" json:"links,omitempty"`
	Categories    []string                     `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	PublishedAt   *timestamppb.Timestamp       `protobuf:"bytes,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedResponse) Reset() {
	*x = GetFeedResponse{}
	mi := &file_proto_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedResponse) ProtoMessage() {}

func (x *GetFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedResponse.ProtoReflect.Descriptor instead.
func (*GetFeedResponse) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{1}
}

func (x *GetFeedResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetFeedResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetFeedResponse) GetImages() []*GetFeedResponse_Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *GetFeedResponse) GetAuthors() []*GetFeedResponse_Person {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *GetFeedResponse) GetEnclosures() []*GetFeedResponse_Enclosure {
	if x != nil {
		return x.Enclosures
	}
	return nil
}

func (x *GetFeedResponse) GetLinks() []string {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *GetFeedResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetFeedResponse) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

type GetFeedResponse_Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedResponse_Person) Reset() {
	*x = GetFeedResponse_Person{}
	mi := &file_proto_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedResponse_Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedResponse_Person) ProtoMessage() {}

func (x *GetFeedResponse_Person) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedResponse_Person.ProtoReflect.Descriptor instead.
func (*GetFeedResponse_Person) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetFeedResponse_Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetFeedResponse_Person) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetFeedResponse_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width         int64                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int64                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedResponse_Image) Reset() {
	*x = GetFeedResponse_Image{}
	mi := &file_proto_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedResponse_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedResponse_Image) ProtoMessage() {}

func (x *GetFeedResponse_Image) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedResponse_Image.ProtoReflect.Descriptor instead.
func (*GetFeedResponse_Image) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetFeedResponse_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetFeedResponse_Image) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GetFeedResponse_Image) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetFeedResponse_Enclosure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Length        int64                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedResponse_Enclosure) Reset() {
	*x = GetFeedResponse_Enclosure{}
	mi := &file_proto_feed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedResponse_Enclosure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedResponse_Enclosure) ProtoMessage() {}

func (x *GetFeedResponse_Enclosure) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedResponse_Enclosure.ProtoReflect.Descriptor instead.
func (*GetFeedResponse_Enclosure) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{1, 2}
}

func (x *GetFeedResponse_Enclosure) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetFeedResponse_Enclosure) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GetFeedResponse_Enclosure) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_proto_feed_proto protoreflect.FileDescriptor

const file_proto_feed_proto_rawDesc = "" +
	"\n" +
	"\x10proto/feed.proto\x12\ahandler\x1a\x1fgoogle/protobuf/timestamp.proto\"\"\n" +
	"\x0eGetFeedRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xbd\x04\n" +
	"\x0fGetFeedResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x126\n" +
	"\x06images\x18\x03 \x03(\v2\x1e.handler.GetFeedResponse.ImageR\x06images\x129\n" +
	"\aauthors\x18\x04 \x03(\v2\x1f.handler.GetFeedResponse.PersonR\aauthors\x12B\n" +
	"\n" +
	"enclosures\x18\x05 \x03(\v2\".handler.GetFeedResponse.EnclosureR\n" +
	"enclosures\x12\x14\n" +
	"\x05links\x18\x06 \x03(\tR\x05links\x12\x1e\n" +
	"\n" +
	"categories\x18\a \x03(\tR\n" +
	"categories\x12=\n" +
	"\fpublished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x1a2\n" +
	"\x06Person\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x1aG\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x03R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x03R\x06height\x1aI\n" +
	"\tEnclosure\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x03R\x06length\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type2R\n" +
	"\x12FeedHandlerService\x12<\n" +
	"\aGetFeed\x12\x17.handler.GetFeedRequest\x1a\x18.handler.GetFeedResponseB\aZ\x05/Feedb\x06proto3"

var (
	file_proto_feed_proto_rawDescOnce sync.Once
	file_proto_feed_proto_rawDescData []byte
)

func file_proto_feed_proto_rawDescGZIP() []byte {
	file_proto_feed_proto_rawDescOnce.Do(func() {
		file_proto_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_feed_proto_rawDesc), len(file_proto_feed_proto_rawDesc)))
	})
	return file_proto_feed_proto_rawDescData
}

var file_proto_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_feed_proto_goTypes = []any{
	(*GetFeedRequest)(nil),            // 0: handler.GetFeedRequest
	(*GetFeedResponse)(nil),           // 1: handler.GetFeedResponse
	(*GetFeedResponse_Person)(nil),    // 2: handler.GetFeedResponse.Person
	(*GetFeedResponse_Image)(nil),     // 3: handler.GetFeedResponse.Image
	(*GetFeedResponse_Enclosure)(nil), // 4: handler.GetFeedResponse.Enclosure
	(*timestamppb.Timestamp)(nil),     // 5: google.protobuf.Timestamp
}
var file_proto_feed_proto_depIdxs = []int32{
	3, // 0: handler.GetFeedResponse.images:type_name -> handler.GetFeedResponse.Image
	2, // 1: handler.GetFeedResponse.authors:type_name -> handler.GetFeedResponse.Person
	4, // 2: handler.GetFeedResponse.enclosures:type_name -> handler.GetFeedResponse.Enclosure
	5, // 3: handler.GetFeedResponse.published_at:type_name -> google.protobuf.Timestamp
	0, // 4: handler.FeedHandlerService.GetFeed:input_type -> handler.GetFeedRequest
	1, // 5: handler.FeedHandlerService.GetFeed:output_type -> handler.GetFeedResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_feed_proto_init() }
func file_proto_feed_proto_init() {
	if File_proto_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_feed_proto_rawDesc), len(file_proto_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_feed_proto_goTypes,
		DependencyIndexes: file_proto_feed_proto_depIdxs,
		MessageInfos:      file_proto_feed_proto_msgTypes,
	}.Build()
	File_proto_feed_proto = out.File
	file_proto_feed_proto_goTypes = nil
	file_proto_feed_proto_depIdxs = nil
}
