// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: subscription.proto

package subscription

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{0}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SubscribeRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *SubscribeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *SubscribeResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type Subscription struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform          string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	ExternalId        string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Url               string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	IntervalSeconds   int32                  `protobuf:"varint,5,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	Enabled           bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LastSeenPublished *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_seen_published,json=lastSeenPublished,proto3" json:"last_seen_published,omitempty"`
	NextCheckAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=next_check_at,json=nextCheckAt,proto3" json:"next_check_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *Subscription) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Subscription) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Subscription) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Subscription) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Subscription) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *Subscription) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Subscription) GetLastSeenPublished() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenPublished
	}
	return nil
}

func (x *Subscription) GetNextCheckAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextCheckAt
	}
	return nil
}

type SubscriptionID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionID) Reset() {
	*x = SubscriptionID{}
	mi := &file_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionID) ProtoMessage() {}

func (x *SubscriptionID) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionID.ProtoReflect.Descriptor instead.
func (*SubscriptionID) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *SubscriptionID) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SetEnabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEnabledRequest) Reset() {
	*x = SetEnabledRequest{}
	mi := &file_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEnabledRequest) ProtoMessage() {}

func (x *SetEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetEnabledRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *SetEnabledRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetEnabledRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type URLMutation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"` // SetEnabledByURL only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLMutation) Reset() {
	*x = URLMutation{}
	mi := &file_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLMutation) ProtoMessage() {}

func (x *URLMutation) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLMutation.ProtoReflect.Descriptor instead.
func (*URLMutation) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *URLMutation) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *URLMutation) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *URLMutation) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *URLMutation) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetIntervalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Interval      *durationpb.Duration   `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetIntervalRequest) Reset() {
	*x = SetIntervalRequest{}
	mi := &file_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetIntervalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIntervalRequest) ProtoMessage() {}

func (x *SetIntervalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIntervalRequest.ProtoReflect.Descriptor instead.
func (*SetIntervalRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *SetIntervalRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SetIntervalRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *SetIntervalRequest) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_subscription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{8}
}

func (x *ListRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ListRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

type ListDueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDueRequest) Reset() {
	*x = ListDueRequest{}
	mi := &file_subscription_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDueRequest) ProtoMessage() {}

func (x *ListDueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDueRequest.ProtoReflect.Descriptor instead.
func (*ListDueRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{9}
}

func (x *ListDueRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ListDueRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_subscription_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{10}
}

func (x *ListResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type AckCursorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckCursorRequest) Reset() {
	*x = AckCursorRequest{}
	mi := &file_subscription_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckCursorRequest) ProtoMessage() {}

func (x *AckCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckCursorRequest.ProtoReflect.Descriptor instead.
func (*AckCursorRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{11}
}

func (x *AckCursorRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AckCursorRequest) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

var File_subscription_proto protoreflect.FileDescriptor

const file_subscription_proto_rawDesc = "" +
	"\n" +
	"\x12subscription.proto\x12\ahandler\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\a\n" +
	"\x05Empty\"a\n" +
	"\x10SubscribeRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"h\n" +
	"\x11SubscribeResponse\x129\n" +
	"\fsubscription\x18\x01 \x01(\v2\x15.handler.SubscriptionR\fsubscription\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"\xbe\x02\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12)\n" +
	"\x10interval_seconds\x18\x05 \x01(\x05R\x0fintervalSeconds\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12J\n" +
	"\x13last_seen_published\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x11lastSeenPublished\x12>\n" +
	"\rnext_check_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vnextCheckAt\" \n" +
	"\x0eSubscriptionID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"=\n" +
	"\x11SetEnabledRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"v\n" +
	"\vURLMutation\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\"\x88\x01\n" +
	"\x12SetIntervalRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x125\n" +
	"\binterval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\binterval\"J\n" +
	"\vListRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\"B\n" +
	"\x0eListDueRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"K\n" +
	"\fListResponse\x12;\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x15.handler.SubscriptionR\rsubscriptions\"a\n" +
	"\x10AckCursorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12=\n" +
	"\fpublished_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt2\xd9\x04\n" +
	"\x13SubscriptionService\x12B\n" +
	"\tSubscribe\x12\x19.handler.SubscribeRequest\x1a\x1a.handler.SubscribeResponse\x126\n" +
	"\vUnsubscribe\x12\x17.handler.SubscriptionID\x1a\x0e.handler.Empty\x125\n" +
	"\x03Get\x12\x17.handler.SubscriptionID\x1a\x15.handler.Subscription\x128\n" +
	"\n" +
	"SetEnabled\x12\x1a.handler.SetEnabledRequest\x1a\x0e.handler.Empty\x127\n" +
	"\x0fSetEnabledByURL\x12\x14.handler.URLMutation\x1a\x0e.handler.Empty\x128\n" +
	"\x10UnsubscribeByURL\x12\x14.handler.URLMutation\x1a\x0e.handler.Empty\x12:\n" +
	"\vSetInterval\x12\x1b.handler.SetIntervalRequest\x1a\x0e.handler.Empty\x123\n" +
	"\x04List\x12\x14.handler.ListRequest\x1a\x15.handler.ListResponse\x129\n" +
	"\aListDue\x12\x17.handler.ListDueRequest\x1a\x15.handler.ListResponse\x126\n" +
	"\tAckCursor\x12\x19.handler.AckCursorRequest\x1a\x0e.handler.EmptyB\x0fZ\r/subscriptionb\x06proto3"

var (
	file_subscription_proto_rawDescOnce sync.Once
	file_subscription_proto_rawDescData []byte
)

func file_subscription_proto_rawDescGZIP() []byte {
	file_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)))
	})
	return file_subscription_proto_rawDescData
}

var file_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_subscription_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: handler.Empty
	(*SubscribeRequest)(nil),      // 1: handler.SubscribeRequest
	(*SubscribeResponse)(nil),     // 2: handler.SubscribeResponse
	(*Subscription)(nil),          // 3: handler.Subscription
	(*SubscriptionID)(nil),        // 4: handler.SubscriptionID
	(*SetEnabledRequest)(nil),     // 5: handler.SetEnabledRequest
	(*URLMutation)(nil),           // 6: handler.URLMutation
	(*SetIntervalRequest)(nil),    // 7: handler.SetIntervalRequest
	(*ListRequest)(nil),           // 8: handler.ListRequest
	(*ListDueRequest)(nil),        // 9: handler.ListDueRequest
	(*ListResponse)(nil),          // 10: handler.ListResponse
	(*AckCursorRequest)(nil),      // 11: handler.AckCursorRequest
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 13: google.protobuf.Duration
}
var file_subscription_proto_depIdxs = []int32{
	3,  // 0: handler.SubscribeResponse.subscription:type_name -> handler.Subscription
	12, // 1: handler.Subscription.last_seen_published:type_name -> google.protobuf.Timestamp
	12, // 2: handler.Subscription.next_check_at:type_name -> google.protobuf.Timestamp
	13, // 3: handler.SetIntervalRequest.interval:type_name -> google.protobuf.Duration
	3,  // 4: handler.ListResponse.subscriptions:type_name -> handler.Subscription
	12, // 5: handler.AckCursorRequest.published_at:type_name -> google.protobuf.Timestamp
	1,  // 6: handler.SubscriptionService.Subscribe:input_type -> handler.SubscribeRequest
	4,  // 7: handler.SubscriptionService.Unsubscribe:input_type -> handler.SubscriptionID
	4,  // 8: handler.SubscriptionService.Get:input_type -> handler.SubscriptionID
	5,  // 9: handler.SubscriptionService.SetEnabled:input_type -> handler.SetEnabledRequest
	6,  // 10: handler.SubscriptionService.SetEnabledByURL:input_type -> handler.URLMutation
	6,  // 11: handler.SubscriptionService.UnsubscribeByURL:input_type -> handler.URLMutation
	7,  // 12: handler.SubscriptionService.SetInterval:input_type -> handler.SetIntervalRequest
	8,  // 13: handler.SubscriptionService.List:input_type -> handler.ListRequest
	9,  // 14: handler.SubscriptionService.ListDue:input_type -> handler.ListDueRequest
	11, // 15: handler.SubscriptionService.AckCursor:input_type -> handler.AckCursorRequest
	2,  // 16: handler.SubscriptionService.Subscribe:output_type -> handler.SubscribeResponse
	0,  // 17: handler.SubscriptionService.Unsubscribe:output_type -> handler.Empty
	3,  // 18: handler.SubscriptionService.Get:output_type -> handler.Subscription
	0,  // 19: handler.SubscriptionService.SetEnabled:output_type -> handler.Empty
	0,  // 20: handler.SubscriptionService.SetEnabledByURL:output_type -> handler.Empty
	0,  // 21: handler.SubscriptionService.UnsubscribeByURL:output_type -> handler.Empty
	0,  // 22: handler.SubscriptionService.SetInterval:output_type -> handler.Empty
	10, // 23: handler.SubscriptionService.List:output_type -> handler.ListResponse
	10, // 24: handler.SubscriptionService.ListDue:output_type -> handler.ListResponse
	0,  // 25: handler.SubscriptionService.AckCursor:output_type -> handler.Empty
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_subscription_proto_init() }
func file_subscription_proto_init() {
	if File_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_proto_depIdxs,
		MessageInfos:      file_subscription_proto_msgTypes,
	}.Build()
	File_subscription_proto = out.File
	file_subscription_proto_goTypes = nil
	file_subscription_proto_depIdxs = nil
}
