// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/setUrl.proto

package setUrl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUrlRequest) Reset() {
	*x = SetUrlRequest{}
	mi := &file_proto_setUrl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUrlRequest) ProtoMessage() {}

func (x *SetUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setUrl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUrlRequest.ProtoReflect.Descriptor instead.
func (*SetUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_setUrl_proto_rawDescGZIP(), []int{0}
}

func (x *SetUrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SetUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	FeedLinks     []string               `protobuf:"bytes,2,rep,name=feed_links,json=feedLinks,proto3" json:"feed_links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUrlResponse) Reset() {
	*x = SetUrlResponse{}
	mi := &file_proto_setUrl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUrlResponse) ProtoMessage() {}

func (x *SetUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_setUrl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUrlResponse.ProtoReflect.Descriptor instead.
func (*SetUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_setUrl_proto_rawDescGZIP(), []int{1}
}

func (x *SetUrlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetUrlResponse) GetFeedLinks() []string {
	if x != nil {
		return x.FeedLinks
	}
	return nil
}

var File_proto_setUrl_proto protoreflect.FileDescriptor

const file_proto_setUrl_proto_rawDesc = "" +
	"\n" +
	"\x12proto/setUrl.proto\x12\ahandler\"!\n" +
	"\rSetUrlRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"I\n" +
	"\x0eSetUrlResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"feed_links\x18\x02 \x03(\tR\tfeedLinks2J\n" +
	"\rSetUrlHandler\x129\n" +
	"\x06SetUrl\x12\x16.handler.SetUrlRequest\x1a\x17.handler.SetUrlResponseB\tZ\a/setUrlb\x06proto3"

var (
	file_proto_setUrl_proto_rawDescOnce sync.Once
	file_proto_setUrl_proto_rawDescData []byte
)

func file_proto_setUrl_proto_rawDescGZIP() []byte {
	file_proto_setUrl_proto_rawDescOnce.Do(func() {
		file_proto_setUrl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_setUrl_proto_rawDesc), len(file_proto_setUrl_proto_rawDesc)))
	})
	return file_proto_setUrl_proto_rawDescData
}

var file_proto_setUrl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_setUrl_proto_goTypes = []any{
	(*SetUrlRequest)(nil),  // 0: handler.SetUrlRequest
	(*SetUrlResponse)(nil), // 1: handler.SetUrlResponse
}
var file_proto_setUrl_proto_depIdxs = []int32{
	0, // 0: handler.SetUrlHandler.SetUrl:input_type -> handler.SetUrlRequest
	1, // 1: handler.SetUrlHandler.SetUrl:output_type -> handler.SetUrlResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_setUrl_proto_init() }
func file_proto_setUrl_proto_init() {
	if File_proto_setUrl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_setUrl_proto_rawDesc), len(file_proto_setUrl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_setUrl_proto_goTypes,
		DependencyIndexes: file_proto_setUrl_proto_depIdxs,
		MessageInfos:      file_proto_setUrl_proto_msgTypes,
	}.Build()
	File_proto_setUrl_proto = out.File
	file_proto_setUrl_proto_goTypes = nil
	file_proto_setUrl_proto_depIdxs = nil
}
