// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/setUrl.proto

package setUrl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SetUrlHandler_SetUrl_FullMethodName = "/handler.SetUrlHandler/SetUrl"
)

// SetUrlHandlerClient is the client API for SetUrlHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SetUrlHandlerClient interface {
	SetUrl(ctx context.Context, in *SetUrlRequest, opts ...grpc.CallOption) (*SetUrlResponse, error)
}

type setUrlHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewSetUrlHandlerClient(cc grpc.ClientConnInterface) SetUrlHandlerClient {
	return &setUrlHandlerClient{cc}
}

func (c *setUrlHandlerClient) SetUrl(ctx context.Context, in *SetUrlRequest, opts ...grpc.CallOption) (*SetUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUrlResponse)
	err := c.cc.Invoke(ctx, SetUrlHandler_SetUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SetUrlHandlerServer is the server API for SetUrlHandler service.
// All implementations must embed UnimplementedSetUrlHandlerServer
// for forward compatibility.
type SetUrlHandlerServer interface {
	SetUrl(context.Context, *SetUrlRequest) (*SetUrlResponse, error)
	mustEmbedUnimplementedSetUrlHandlerServer()
}

// UnimplementedSetUrlHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSetUrlHandlerServer struct{}

func (UnimplementedSetUrlHandlerServer) SetUrl(context.Context, *SetUrlRequest) (*SetUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUrl not implemented")
}
func (UnimplementedSetUrlHandlerServer) mustEmbedUnimplementedSetUrlHandlerServer() {}
func (UnimplementedSetUrlHandlerServer) testEmbeddedByValue()                       {}

// UnsafeSetUrlHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SetUrlHandlerServer will
// result in compilation errors.
type UnsafeSetUrlHandlerServer interface {
	mustEmbedUnimplementedSetUrlHandlerServer()
}

func RegisterSetUrlHandlerServer(s grpc.ServiceRegistrar, srv SetUrlHandlerServer) {
	// If the following call panics, it indicates UnimplementedSetUrlHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SetUrlHandler_ServiceDesc, srv)
}

func _SetUrlHandler_SetUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetUrlHandlerServer).SetUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetUrlHandler_SetUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetUrlHandlerServer).SetUrl(ctx, req.(*SetUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SetUrlHandler_ServiceDesc is the grpc.ServiceDesc for SetUrlHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SetUrlHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "handler.SetUrlHandler",
	HandlerType: (*SetUrlHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetUrl",
			Handler:    _SetUrlHandler_SetUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/setUrl.proto",
}
